name: Build and Publish Docker Image

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: |
            x86_64-unknown-linux-musl
            aarch64-unknown-linux-musl

      - name: Install Zig
        uses: mlugg/setup-zig@v2
        with:
          version: 0.13.0

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2

      - name: Install cargo-zigbuild
        run: cargo install cargo-zigbuild --locked

      - name: Set version
        id: version
        run: |
          if [ "${GITHUB_REF_TYPE}" = "tag" ]; then
            VERSION="${GITHUB_REF_NAME}"
          elif [ "${GITHUB_REF_TYPE}" = "branch" ] && [ "${GITHUB_REF_NAME}" = "master" ]; then
            VERSION="nightly"
          else
            VERSION="${GITHUB_REF_NAME}"
          fi

          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - run: mkdir -p dist

      - name: Build X86-64
        run: |
          cargo zigbuild --release --target x86_64-unknown-linux-musl
          cp target/x86_64-unknown-linux-musl/release/cache_cat dist/cache_cat-x86_64

      - name: Build AARCH64
        run: |
          cargo zigbuild --release --target aarch64-unknown-linux-musl
          cp target/aarch64-unknown-linux-musl/release/cache_cat dist/cache_cat-aarch64

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: dist/*
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v2
      #   with:
      #     platforms: all

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2

      # - name: Log in to GHCR
      #   uses: docker/login-action@v2
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Run build-docker.sh
      #   run: |
      #     PUSH_IMAGE="ghcr.io/${{ github.repository_owner }}/${{ github.repository }}" \
      #       bash scripts/build-docker.sh

      # - name: Push Docker image to GHCR
      #   run: |
      #     # Extract image tag from build-docker.sh or set it manually
      #     IMAGE_NAME="ghcr.io/${{ github.repository_owner }}/${{ github.repository }}"
      #     docker push "$IMAGE_NAME"
