name: Publish Artifacts to Release

on:
  workflow_call:

jobs:
  push-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v8

      - name: Set image tag
        id: vars
        run: |
          if [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
            echo "image_tag=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
            echo "is_tag=true" >> $GITHUB_OUTPUT
            echo "is_prerelease=false" >> $GITHUB_OUTPUT
          else
            echo "image_tag=latest" >> $GITHUB_OUTPUT
            echo "is_tag=false" >> $GITHUB_OUTPUT
            echo "is_prerelease=true" >> $GITHUB_OUTPUT
          fi

      - name: Rename files
        run: |
          mkdir -p release
          find -type f | grep -E 'cache_cat$' | while read line; do
            dest_file=$(basename $line)$(echo $line | awk -F '/' '{print $2}' | sed 's/cache_cat//g')
            echo "Source: $line"
            echo "Target: $dest_file"
            cp $line release/$dest_file
            sha256sum $line > release/${dest_file}.sha256
          done

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.vars.outputs.image_tag }}
          release_name: ${{ github.ref_name }}
          body: "This is an automated release."
          draft: false
          prerelease: ${{ steps.vars.outputs.is_prerelease }}
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          files: release/*