name: Build and Upload Artifacts

on:
  workflow_dispatch:
  workflow_call:
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: |
            x86_64-unknown-linux-musl
            aarch64-unknown-linux-musl
            riscv64gc-unknown-linux-musl
            armv7-unknown-linux-musleabihf
            # s390x-unknown-linux-musl
            # loongarch64-unknown-linux-musl

      - name: Install Zig
        uses: mlugg/setup-zig@v2
        with:
          version: 0.13.0

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2

      - name: Install cargo-zigbuild
        run: cargo install cargo-zigbuild --locked

      - name: Fetch
        run: make fetch

      - name: Build
        run: |
          mkdir -p dist
          make all -j4

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output.zip
          path: |
            dist/