name: Build and Upload Artifacts

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - toolchain: x86_64-unknown-linux-musl
            target: linux-amd64
            os: ubuntu-latest
            llvm: false

          - toolchain: riscv64gc-unknown-linux-musl
            target: linux-riscv64
            os: ubuntu-latest
            llvm: false

          - toolchain: aarch64-unknown-linux-musl
            target: linux-arm64
            os: ubuntu-latest
            llvm: false

          - toolchain: aarch64-apple-darwin
            target: macos-arm64
            os: macos-latest-arm
            llvm: false

          - toolchain: x86_64-pc-windows-msvc
            target: win-x64
            os: windows-latest
            llvm: true

          - toolchain: aarch64-pc-windows-msvc
            target: win-arm64
            os: windows-latest-arm
            llvm: true

    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Xcode for macOS targets
        if: matrix.os == 'macos-latest-arm'
        run: |
          xcodebuild -version
          xcrun --sdk macosx --show-sdk-path
          echo "SDKROOT=$(xcrun --sdk macosx --show-sdk-path)" >> $GITHUB_ENV
          echo "DEVELOPER_DIR=$(xcode-select -p)" >> $GITHUB_ENV

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.toolchain }}

      - name: Install Zig
        uses: mlugg/setup-zig@v2
        with:
          version: 0.13.0
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v2
        if: matrix.llvm == 'true'
        with:
          version: 18
      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2

      - name: Install cargo-zigbuild
        run: cargo install cargo-zigbuild --locked

      - name: Build
        if: matrix.target != 'macos-arm64'
        run: |
          cargo zigbuild --release --target ${{ matrix.toolchain }} --bin cache_cat --bin cache_cat_ping
      - name: Build MacOS
        if: matrix.target == 'macos-arm64'
        run: |
          cargo build --release --target ${{ matrix.toolchain }} --bin cache_cat --bin cache_cat_ping
      - name: Upload artifact CacheCat
        uses: actions/upload-artifact@v4
        with:
          name: cache_cat-${{matrix.target}}
          path: |
            target/${{matrix.toolchain}}/release/cache_cat
            target/${{matrix.toolchain}}/release/cache_cat_ping

  publish-docker:
    needs: build
    uses: ./.github/workflows/docker-build-publish.yaml

  publish-artifacts:
    needs: build
    uses: ./.github/workflows/github-release-publish.yaml
